# Dialout is free and MIT licensed. Its development is sponsored by IndiaNIC,
# which also offers customisation, integration and managed deployment for teams
# that want it. The Sponsor button points there rather than at a donation page —
# there is nothing to donate to.
custom:
  - https://www.indianic.com
